
import "./globals.css";


export const metadata = {
  title: "Some interesting app with Musabbir",
  description: "Generated by Musabbir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
